famous/famous/urls.py
from django.contrib import admin
from django.urls import path
from collection import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('mov', views.movies),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

famous/collection/models.py
from django.db import models

class movie(models.Model):
    movieid = models.CharField(max_length=100)
    moviename = models.CharField(max_length=100)
    moviedirector= models.CharField(max_length=100)
    releasedate = models.DateField(null=True)

    class Meta:
        db_table = "movie"

famous/collection/forms.py
from django import forms
from .models import movie

class movieform(forms.ModelForm):
    class Meta:
        model = movie
        fields = "__all__"

famous/collection/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import movieform
from .models import movie

def index(request):
    print(request.GET)
    return render(request, "home.html")

def movies(request):
    if request.method == "POST":
        form = movieform(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = movieform()
    return render(request,'index.html',{'form':form})

def show(request):
    Movie = movie.objects.all()
    return render(request,"show.html",{'movie':Movie})

def edit(request, id):
    editmovie = movie.objects.get(id=id)
    return render(request,'edit.html',{'movie':editmovie})

def update(request, id):
    editmovie = movie.objects.get(id=id)
    form = movieform(request.POST, instance =editmovie)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'movie': editmovie})

def destroy(request, id):
    editmovie = movie.objects.get(id=id)
    editmovie.delete()
    return redirect("/show")

famous/collection/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
</head>
<style>
    body
    {
    background-color:cyan;
    }
</style>
<body>
<center>
<form method="POST" class="post-form" action="/update/{{movie.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label></label>
    <div>
    <h2>Update Movie Details</h2>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"><b>Movie Id:</b></label>
    <div class="col-sm-4">
       <input type="text" name="movieid" id="id_moveid" required maxlength="100" value="{{ movie.movieid }}"/>
    </div>
  </div><br>
  <div class="form-group row">
    <label><b>Movie Name:</b></label>
    <div class="col-sm-4">
        <input type="text" name="moviename" id="id_moviename" required maxlength="100" value="{{ movie.moviename }}" />
    </div>
  </div><br>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"><b>Movie Director:<b></b></label>
    <div class="col-sm-4">
        <input type="text" name="moviedirector" id="id_moviedirector" required maxlength="254" value="{{ movie.moviedirector }}" />
    </div>
  </div><br>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"><b>Release Date:</b></label>
    <div class="col-sm-4">
        <input type="date" name="releasedate" id="id_releasedate" required maxlength="15" value="{{ movie.releasedate }}" />
    </div>
  </div><br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success"><b>Update</b></button>
    </div>
  </div>
    </div>
</form>
</center>
</body>
</html>

famous/collection/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Home </title>
</head>
{% load static %}
<style>

    body
    {
    background-image:url("static/dog.jpg");
    webkit-background-size: cover;
    moz-background-size: cover;
    o-background-size: cover;
    background-size: cover;
    }

</style>
<body>
<center>

    <h1 style="color:black;"> Hello Guys. Your at Movie's Collections.</h1>
    <h4 style="text-align:left;"><a  href="/admin" class="btn btn-primary">Admin</a></h4>
    <br>
    <h2 style="color:black;"><a href="/mov" >Add New Movie Record</a></h2><br><br>
    <h2 style="color:black;"><a href="/show">View The Movie's Record</a></h2>

</center>
</body>
</html>

famous/collection/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
{% load static %}
<style>
    body
    {
    background-image:url("static/win.jpg");
    webkit-background-size: cover;
    moz-background-size: cover;
    o-background-size: cover;
    background-size: cover;
    }
</style>
<body>
<center>
<form method="POST" class="post-form" action="/mov">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h1 style="color:white;background-color:black;"> Enter the Movies Details</h1>
    </div>
  </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label"><h4 style="color:white;">Movie Id:</h4></label>
    <div class="col-sm-4">
      {{ form.movieid }}
    </div>
  </div>
  <div class="form-group row">
      <label class="col-sm-2 col-form-label"><h4 style="color:white;">Movie Name:</h4></label>
    <div class="col-sm-4">
      {{ form.moviename }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"><h4 style="color:white;">Movie Director:</h4></label>
    <div class="col-sm-4">
      {{ form.moviedirector }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"><h4 style="color:white;">Release Date:</h4></label>
    <div class="col-sm-4">
      {{ form.releasedate }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4"><br>
        <button type="submit" class="btn btn-primary"><b>Submit</b></button>
    </div>
  </div>
    </div>
</form>
</center>>
</body>
</html>

famous/collection/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie Records</title>
    {% load static %}
</head>
<style>
    body
    {
    background-image:url("static/a.jpg");
    webkit-background-size: cover;
    moz-background-size: cover;
    o-background-size: cover;
    background-size: cover;
    }
    th, td {
  padding: 12px;}

</style>
<body>
<center>
<table style="width:40%">
    <caption><h2>Movie Records</h2> </caption>
    <thead class="thead-dark">
    <tr>
        <th>Movie ID</th>
        <th>Movie Name</th>
        <th>Movie Director</th>
        <th>Release Date</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for movie in movie %}
    <tr><br>
        <td>{{ movie.movieid }}</td>
        <td>{{ movie.moviename }}</td>
        <td>{{ movie.moviedirector }}</td>
        <td>{{ movie.releasedate }}</td>
        <td>
            <a href="/edit/{{ movie.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ movie.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<br>
<br>
<center><b><a href="/mov" class="btn btn-primary">Add New Movie Record</a></b></center>
</center>
</body>
</html>